### ISSUE TITLE
Another locked file crash.

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#67] opened 2020-05-11 22:41 UTC
[2020-05-11_Error.log](https://github.com/bcssov/IronyModManager/files/4612444/2020-05-11_Error.log)

Had just copied all my mods into the local mod folder after tidying up. Mods are still in the steam folder also.

The crash happened just after I right-clicked > delete all and reload and was scrolling down the list. There are currently some 400 odd items in said list.

**Comment by bcssov** [comment] 2020-05-12 00:04
That mod is where it crashed is distributed as a zip? If so you probably have 2 zips in mod folder with the same filename. Irony scans first level directories in mod folder for signs of zip files (as they are downloaded as such via pdx launcher) and generates descciptor filenames based on their filename convention and or parent directory name. This is not an issue as I see as it and something that needs fixing.

**Comment by LordOfLA** [comment] 2020-05-12 00:35
No, I make sure mods are unzipped with a python script, I made visually sure as well when copying out of the workshop folder.

**Comment by bcssov** [comment] 2020-05-12 00:51
I cannot reproduce this. Did you tick multiple times maybe delete and reload?

**Comment by LordOfLA** [comment] 2020-05-12 00:56
Nope, only once and started scrolling the list.

**Comment by bcssov** [comment] 2020-05-12 01:07
That's all that I can think of. Can't reproduce.

**Comment by bcssov** [comment] 2020-05-12 15:43
Added retry strategy, other than that this is a non repro issue. Closing.

**Closed by bcssov** 2020-05-12 15:43 UTC
Labels: question, unable to reproduce
