### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by Zerafir** [bcssov/IronyModManager#79] opened 2020-06-09 18:25 UTC
Save Error when applying collection mod ordering to the game.
Message:
Save Error
Something seems to locking Irony's ability to write to mod files.
Please report this on GitHub issue tracker and post the error log.

[2020-06-09_Error.log](https://github.com/bcssov/IronyModManager/files/4754065/2020-06-09_Error.log)

**Comment by bcssov** [comment] 2020-06-09 18:45
This part of the error log: `1. Path '', line 1, position 10216`. is stating the one of the jsons generated by pdx launcher: **game_data.json**, **dlc_load.json** or most likely **mod_registry.json i**s corrupt. Or there is something unexpected in them, to debug properly I'd need you to share these with me if possible otherwise there's nothing I can do.

**Comment by bcssov** [comment] 2020-06-09 18:52
Alternatively you can delete these files, but I'd like to have a look at them. If you're worried about publicly sharing them then upload somewhere and message me on Modding Den discord with a download link.

**Comment by Zerafir** [comment] 2020-06-09 18:57
Ok here the three .json files

[game_data.zip](https://github.com/bcssov/IronyModManager/files/4754240/game_data.zip)

**Comment by bcssov** [comment] 2020-06-09 19:01
Your game_data.json was corrupt, what did you use before that caused this piece to be written:
```"isEulaAccepted":true}1-c446f37b304e"],"isEulaAccepted":true}```
Everything after
```"isEulaAccepted":true}```
is invalid json formatting.

**Comment by Zerafir** [comment] 2020-06-09 19:13
Had Stellaris running the old 2.6.2 after the 2.7 release for a while, than stopped playing a couple weeks ago, updated to 2.7.2 yesterday got the Mod Manager v1.0.133. with this collection which gave me this error message switched to v1.1.91-alpha. which still showed me this error and than wrote here about it.
That's pretty much all.

**Comment by bcssov** [comment] 2020-06-09 21:17
Has to be something more, but the issue is solved so closing this ticket now.

**Closed by bcssov** 2020-06-09 21:17 UTC
Labels: wontfix
