### ISSUE TITLE
Planet classes in Stellaris

### ISSUE THREAD

**Issue by Virstag** [bcssov/IronyModManager#104] opened 2020-08-28 15:53 UTC
I think there is an issue with the way IronyModManager handles the contents of the "common/planet_classes" folder. More specifically, it's about the "atmosphere_color" parameter. Normally, it looks like this:

`atmosphere_color 		= hsv { 0.75 0.10 0.60 }`

After processing, it looks like this:

 ```
atmosphere_color = {
        0.75
        0.1
        0.6
    }
```

The missing "hsv" changes the colors of planets and stars to completely different than intended. Manually adding "hsv" solves the problem.

Best regards

**Comment by bcssov** [comment] 2020-08-28 17:54
Nothing I can do at the moment, this is caused by CWTools parser failing. Will be resolved in a parser rewrite on my end.

**Comment by bcssov** [comment] 2020-09-01 17:19
New parsers should resolve that, cwtools have fallen back to validation only role.

**Closed by bcssov** 2020-09-01 17:19 UTC
Labels: bug
