### ISSUE TITLE
Several problems on Mac Big Sur OS version v1.21.131

### ISSUE THREAD

**Issue by madmotorcyclist** [bcssov/IronyModManager#353] opened 2022-04-13 16:06 UTC
Stellaris run, I am getting out of memory errors when merging.  In addition got this error below when using Conflict Analysis.  Prior version had none of these issues.

Unhandled error ocurred. Please use this information to file a bug report:

2022-04-13 08:56:13.8875 Version: 1.21.131+f60aeacd91
OS Description: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
Runtime Identifier: osx.11.0-x64
 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.AggregateException: One or more errors occurred. (Length cannot be less than zero. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at IronyModManager.Parser.Generic.KeyParser.CanParse(CanParseArgs args) in D:\Working\IronyModManager\src\IronyModManager.Parser\Generic\KeyParser.cs:line 87
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at IronyModManager.Parser.ParserManager.InvokeParsers(ParserManagerArgs args) in D:\Working\IronyModManager\src\IronyModManager.Parser\ParserManager.cs:line 294
   at IronyModManager.Parser.ParserManager.Parse(ParserManagerArgs args) in D:\Working\IronyModManager\src\IronyModManager.Parser\ParserManager.cs:line 121
   at IronyModManager.Services.ModPatchCollectionService.ParseModFiles(IGame game, IEnumerable`1 fileInfos, IModObject modObject) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 2404
   at IronyModManager.Services.ModPatchCollectionService.<>c__DisplayClass26_0.<GetModObjectsAsync>b__0(IMod m) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 661
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at IronyModManager.Services.ModPatchCollectionService.GetModObjectsAsync(IGame game, IEnumerable`1 mods, String collectionName) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 658
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass141_0.<<AnalyzeModsAsync>b__1>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 488
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(Int64 id, PatchStateMode mode, IEnumerable`1 versions) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 486
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass146_0.<<OnActivated>g__runAnalysis|0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 683
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 73
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 559
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4345
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 96

**Comment by bcssov** [comment] 2022-04-13 18:08
> Stellaris run, I am getting out of memory errors when merging. In addition got this error below when using Conflict Analysis. Prior version had none of these issue

If I keep filestreams open then we end up with too many file handles open so not sure I can do much about that.

As for the error message this is caused by a mod though it's unclear from the exception. Can you narrow it down for me to a mod or 2?

**Comment by madmotorcyclist** [comment] 2022-04-14 14:14
I’m running a two tests now, but it requires me to fully play out a two games which takes times.  Yes, it could be a conflict that you mention (in an earlier Stellaris game near the last one-third time frame I’ve hit an illegal instruction 04 that aborted the game.  I’ve read from other forums that there appears to be a conflict between the NSC2 Season 6 (an extensive ship design mod) and the Aquatics DLC.

Right now, I’m running a Stellaris game (same everything) with merged Irony Mod Manager of my mods with NSC2 but the game is without the Aquatics DLC to see if that eliminates the illegal instruction abort.  After that I then will run a game with the Aquatics DLC and without NSC2 Irony merge.  If both games run all the way to the end time without aborting I think we can verify what is rumored on the forums.

**Comment by bcssov** [comment] 2022-04-14 15:47
There's nothing I can do about the game crashes I am interested in the conflict solver crash only. The illegal instruction is a mod or a game issue that is beyond the scope of this tool.

**Comment by madmotorcyclist** [comment] 2022-04-14 21:27
Well, I can say that bug in the game is not from what I thought.  However, to help you get to the problem here’s the list of mods in order I run with all DLCs for Stellaris causing the out of memory errors when merging:

Music Pack, SpaceAmbient Music - Vol. I, SpaceAmbient Music - Vol. II, Merged Leader Levels, Enhanced Galaxy 2.3: Dark Core, Beautiful Universe v2.0, Archaeology Story Pack, Trace’s Better Lithoids, Even More Origins, No Clustered Starts, Precursor Story Pack, Guilli’s Planet Modifiers and Features, Guillified Precursor Story Pack, Gigastructural Engineering & More (3.3), Machine Shipset, Extra Ship Components NEXT, Plentiful Traditions 3.x, UI Overhaul Dynamic, UI Overhaul Dynamic - More Tradition Categories (32), Planetary Diversity, UI Overhaul Dynamic + Planetary Diversity, !!!Universal Resource Patch [2.4+], !!Universal Modifier Patch (3.3.*), (-NSC2 Season 6).

Note: This same list merges just fine with the prior version of Irony Mod Manager v1.21.122

**Comment by bcssov** [comment] 2022-04-14 21:48
Merging with 122 or with 131 the same code and logic is executed. In my initial response I explained what causes out of memory issues probably and why there's very little I can do about it on a Mac machine.

As for the other error, that's way too many mods I will wait until another report comes from someone else to allow us to narrow this conflict solver CTD to a single mod.

**Comment by Nestef** [comment] 2022-04-15 19:44
I can confirm I am having the same crash on Linux. The only mod that causes this on my modlist is Gigastructural Engineering.

**Comment by bcssov** [comment] 2022-04-15 20:16
Game crashes are reported to paradox or the mod team in question. This topic has served its purpose. I will close it now.

**Closed by bcssov** 2022-04-15 20:16 UTC
Labels: question
