### ISSUE TITLE
Save Error; Mods Not Loading

### ISSUE THREAD

**Issue by Dreams-of-Fulda** [bcssov/IronyModManager#427] opened 2023-03-09 03:53 UTC
**Describe the bug**
This may be two separate bugs which happen to have popped up at the same time.
When I apply a collection or launch Hearts of Iron 4 (or possibly other games; I haven't tested with them) I get a message saying:
Save Error
Something seems to be locking Irony's ability to write mod files.  Please Report this on GitHub issue tracker and post the error log.
If I've hit launch game, the game then launches.

Additionally, roughly half my mods have simply stopped loading, whether through Irony or the Paradox launcher.  They show up in the manager/launcher, I can enable them without issue, but they have no effect on the game once it starts.  There doesn't seem to be any rhyme or reason to which mods are effected, other than that local mods work just fine (including local copies of mods downloaded from Steam).  Some of them are mods which just updated, but many are not, and have worked fine in the recent past, so it does not seem to be an issue on their part.

**To Reproduce**
I can reproduce the "Save Error" message just by applying a collection.
The failure of mods to load, I can reproduce by trying to start the game with a collection including any of a number of mods, including Kaiserredux, Ultimate Tech Tree: New Horizons, or Commander and Admiral Traits: By Blood Alone addtion (sic).

**Expected behavior**
I would not get the "Save Error" message.  
The game would load all the mods I have enabled.

**Version:**
 - OS:  Windows 10
 - Irony Version: 1.24.114

**Additional context**
[2023-03-08_Error.log](https://github.com/bcssov/IronyModManager/files/10927426/2023-03-08_Error.log)

**Comment by Dreams-of-Fulda** [comment] 2023-03-10 04:52
Reinstalling HoI4 got rid of the "Save Error" and the mods failing to load turned out to be an issue with my anti-virus.

**Comment by bcssov** [comment] 2023-03-10 05:12
Closing, duplicate of: https://github.com/bcssov/IronyModManager/issues/426

**Closed by bcssov** 2023-03-10 05:12 UTC
Labels: duplicate
