### ISSUE TITLE
Something Seems to Be Locking the Mod Manager's Ability to Write to Mod Files

### ISSUE THREAD

**Issue by TurtleShroom** [bcssov/IronyModManager#457] opened 2023-07-26 21:43 UTC
**Describe the bug**
When I click "APPLY" to apply a new set of Mods on the "Crusader Kings III" video game, the Launcher refuses and claims access is denied.

**To Reproduce**

When I click "APPLY" to apply a new set of Mods on the "Crusader Kings III" video game, the Launcher refuses and claims access is denied.. 

**Expected behavior**

I expected my chosen series of Mods to be applied to the dog crap Paradox Launcher by the Irony Mod Manager program.

**Logs**
If the application crashed add error logs related to the crash.
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2243170894.mod line: 7
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2322286437.mod line: 7
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2473115238.mod line: 7
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2493459927.mod line: 8
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2561941461.mod line: 6
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2700696193.mod line: 16
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2758929181.mod line: 8
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2779600959.mod line: 7
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2790872361.mod line: 10
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2810675254.mod line: 7
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2863120557.mod line: 9
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2891354875.mod line: 7
[17:36:41][dlc_descriptor.cpp:70]: Invalid supported_version in  file: mod/ugc_2891641440.mod line: 7
[17:37:04][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueFloat' in 'RandomizableValueFloat.GetValue'.
[17:37:04][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueFloat' in 'RandomizableValueFloat.GetValue'.
[17:37:04][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueFloat.GetValue'
[17:37:04][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueFloat' in 'RandomizableValueFloat.SetValue'.
[17:37:04][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueFloat' in 'RandomizableValueFloat.SetValue'.
[17:37:04][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueFloat.SetValue'
[17:37:04][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:48 - Failed parsing data statement 'RandomizableValueFloat.SetValue' for property 'oneditingfinished'(853)

[17:37:04][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueFloat' in 'RandomizableValueFloat.Randomize'.
[17:37:04][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueFloat' in 'RandomizableValueFloat.Randomize'.
[17:37:04][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueFloat.Randomize'
[17:37:04][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:53 - Failed parsing data statement 'RandomizableValueFloat.Randomize' for property 'onclick'(775)

[17:37:36][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueInt' in 'RandomizableValueInt.GetValue'.
[17:37:36][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueInt' in 'RandomizableValueInt.GetValue'.
[17:37:36][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueInt.GetValue'
[17:37:36][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueInt' in 'RandomizableValueInt.SetValue'.
[17:37:36][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueInt' in 'RandomizableValueInt.SetValue'.
[17:37:36][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueInt.SetValue'
[17:37:36][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:70 - Failed parsing data statement 'RandomizableValueInt.SetValue' for property 'oneditingfinished'(853)

[17:37:36][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueInt' in 'RandomizableValueInt.Randomize'.
[17:37:36][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueInt' in 'RandomizableValueInt.Randomize'.
[17:37:36][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueInt.Randomize'
[17:37:36][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:75 - Failed parsing data statement 'RandomizableValueInt.Randomize' for property 'onclick'(775)

[17:37:53][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueFloat' in 'RandomizableValueFloat.GetValue'.
[17:37:53][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueFloat' in 'RandomizableValueFloat.GetValue'.
[17:37:53][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueFloat.GetValue'
[17:37:53][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueFloat' in 'RandomizableValueFloat.SetValue'.
[17:37:53][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueFloat' in 'RandomizableValueFloat.SetValue'.
[17:37:53][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueFloat.SetValue'
[17:37:53][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:93 - Failed parsing data statement 'RandomizableValueFloat.SetValue' for property 'oneditingfinished'(853)

[17:37:53][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueFloat' in 'RandomizableValueFloat.Randomize'.
[17:37:53][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueFloat' in 'RandomizableValueFloat.Randomize'.
[17:37:53][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueFloat.Randomize'
[17:37:53][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:98 - Failed parsing data statement 'RandomizableValueFloat.Randomize' for property 'onclick'(775)

[17:37:58][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.Search'.
[17:37:58][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.Search'.
[17:37:58][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.Search'
[17:37:58][pdx_gui_factory.cpp:907]: gui/toolspropertytypes.gui:424 - Failed parsing data statement 'FilterablePropertyList.Search' for property 'ontextchanged'(854)

[17:37:58][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.GetSearchText'.
[17:37:58][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.GetSearchText'.
[17:37:58][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.GetSearchText'
[17:37:58][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.ClearSearchText'.
[17:37:58][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.ClearSearchText'.
[17:37:58][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.ClearSearchText'
[17:37:58][pdx_gui_factory.cpp:907]: gui/toolspropertytypes.gui:432 - Failed parsing data statement 'FilterablePropertyList.ClearSearchText' for property 'onclick'(775)

[17:37:58][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.GetPropertiesLabel'.
[17:37:58][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.GetPropertiesLabel'.
[17:37:58][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.GetPropertiesLabel'
[17:37:59][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.Search'.
[17:37:59][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.Search'.
[17:37:59][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.Search'
[17:37:59][pdx_gui_factory.cpp:907]: gui/toolspropertytypes.gui:424 - Failed parsing data statement 'FilterablePropertyList.Search' for property 'ontextchanged'(854)

[17:37:59][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.GetSearchText'.
[17:37:59][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.GetSearchText'.
[17:37:59][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.GetSearchText'
[17:37:59][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.ClearSearchText'.
[17:37:59][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.ClearSearchText'.
[17:37:59][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.ClearSearchText'
[17:37:59][pdx_gui_factory.cpp:907]: gui/toolspropertytypes.gui:432 - Failed parsing data statement 'FilterablePropertyList.ClearSearchText' for property 'onclick'(775)

[17:37:59][pdx_data_factory.cpp:1344]: Failed to find type 'FilterablePropertyList' in 'FilterablePropertyList.GetPropertiesLabel'.
[17:37:59][pdx_data_factory.cpp:1351]: Could not find promote for 'FilterablePropertyList' in 'FilterablePropertyList.GetPropertiesLabel'.
[17:37:59][pdx_data_factory.cpp:1032]: Failed converting statement for 'FilterablePropertyList.GetPropertiesLabel'
[17:38:00][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueInt' in 'RandomizableValueInt.GetValue'.
[17:38:00][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueInt' in 'RandomizableValueInt.GetValue'.
[17:38:00][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueInt.GetValue'
[17:38:00][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueInt' in 'RandomizableValueInt.SetValue'.
[17:38:00][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueInt' in 'RandomizableValueInt.SetValue'.
[17:38:00][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueInt.SetValue'
[17:38:00][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:115 - Failed parsing data statement 'RandomizableValueInt.SetValue' for property 'oneditingfinished'(853)

[17:38:00][pdx_data_factory.cpp:1344]: Failed to find type 'RandomizableValueInt' in 'RandomizableValueInt.Randomize'.
[17:38:00][pdx_data_factory.cpp:1351]: Could not find promote for 'RandomizableValueInt' in 'RandomizableValueInt.Randomize'.
[17:38:00][pdx_data_factory.cpp:1032]: Failed converting statement for 'RandomizableValueInt.Randomize'
[17:38:00][pdx_gui_factory.cpp:907]: gui/tool_property_randomizable_types.gui:120 - Failed parsing data statement 'RandomizableValueInt.Randomize' for property 'onclick'(775)

**Version:**
 - OS: "Windows VII"
 - Irony Mod Manager Version: V1.24.107

**Comment by bcssov** [comment] 2023-07-26 23:38
This is the wrong log, I need Irony Mod Manager error log not CK3 error log.

**Comment by TurtleShroom** [comment] 2023-07-27 02:35
E-MAIL REPLY

How do I give that to you? I clicked the "VIEW LOG" button in the actual Mod Manager UI. I will try again.

<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

 <targets>
 <target name="logger" xsi:type="IronyFile"
 fileName="${specialfolder:folder=ApplicationData}/Mario/IronyModManager-Logs/${date:format=yyyy-MM-dd}_${level}.log"
 layout="${longdate} ${message} ${exception:format=tostring}" maxArchiveDays="10"/>
 <target name="logconsole" xsi:type="Console"/>
 <target name="trace" xsi:type="trace" layout="Layout"/>
 </targets> 
 
 <rules>
 <logger name="*" minLevel="Error" writeTo="logger"/>
 <logger name="*" minlevel="Error" writeTo="logconsole"/>
 <logger name="*" minLevel="Error" writeTo="trace"/>
 </rules>
</nlog>

Is that it?

------
Jesus Loves You and Died for You!

     On Wednesday, July 26, 2023 at 07:38:33 PM EDT, Mario ***@***.***> wrote:  
 
 


This is the wrong log, I need Irony Mod Manager error log not CK3 error log.

**Comment by bcssov** [comment] 2023-07-27 03:22
This is not the Irony error log. Go to Irony homepage: https://bcssov.github.io/IronyModManager/ and check Issues\Bugs section.

**Comment by TurtleShroom** [comment] 2023-07-28 16:51
[2023-01-07_Fatal.zip](https://github.com/bcssov/IronyModManager/files/12196577/2023-01-07_Fatal.zip)


Why would you hide the logs in such a terrible place? Why not just put them in the Program Files where your program is installed?

**Comment by bcssov** [comment] 2023-07-28 19:41
1. 1.24.x version is no longer supported
2. Irony doesn't support multiple instances
3. This incompatibility with pdx launcher (caused by pdx launcher changes) that you reported was fixed several Irony versions ago. Upgrade to latest Irony version.

Closing ticket

**Closed by bcssov** 2023-07-28 19:41 UTC
Labels: question

**Comment by TurtleShroom** [comment] 2023-07-30 01:53
Thank you. I will let you know if it worked.

**Comment by TurtleShroom** [comment] 2023-07-30 03:11
It worked! Thank you so much, and I apologize for bothering you with such a stupidly trivial mistake on my part!
