### ISSUE TITLE
Attempting to remove existing collection results in CTD.

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#56] opened 2020-05-03 17:43 UTC
Not sure if the log will be helpful. Essentially I pressed the - button to remove the only existing collection defined and Irony disappeared silently to desktop.

Edit: So I made a new collection, tried to remove the other one, same result.

[2020-05-03_Error.log](https://github.com/bcssov/IronyModManager/files/4571149/2020-05-
03_Error.log)

**Comment by bcssov** [comment] 2020-05-03 17:52
I know, I know. It's a duplicate of this #53. When I was changing app icons Visual Studio decided to exclude app icons from being embedded. That's what's crashing. 1.0.83 will be up shortly.

**Closed by bcssov** 2020-05-03 17:52 UTC
Labels: duplicate
