### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by Colonizor48** [bcssov/IronyModManager#221] opened 2021-03-27 04:51 UTC
**Describe the bug**
Irony mod manager is very laggy for me. And it randomly crashes. It started after getting a new pc. The pc is a bit old(its still a great pc just old) So that might have somthing to do with it
**To Reproduce**
1.  Open the program
2.  Notice it is super laggy
3.  Wait
4.  It crashes

**Expected behavior**
A non laggy program that doesnt crash

**Screenshots**
N/A

**Logs**
[2021-03-27_Error.log](https://github.com/bcssov/IronyModManager/files/6215144/2021-03-27_Error.log)

**Version:**
Windows 10

V1.12.126

**Additional context**
I have this installed on my hard drive instead of my ssd. That might add to it somewhat. IDK why it would but it might.

**Comment by bcssov** [comment] 2021-03-27 05:13
First 1.12 has reached end of life and is no longer supported.

Second on most tested modern PCs there is no lag that I know of. There's very little I can do for lags on where it happens though. The crash seems to be caused by the lag though as the objects seemed to have been disposed.

**Comment by Colonizor48** [comment] 2021-03-27 05:18
Ill try updating. For the record here are my specs.
CPU: Xeon x3470 2.9ghz
GPU: GTX 1050 2gb
RAM: 12gb
HDD: 500gb
SSD: 230gb

**Comment by Colonizor48** [comment] 2021-03-30 23:36
No more crashing after updating but still lag.

**Comment by bcssov** [comment] 2021-03-31 04:32
Not much I can do. Lag implies either a software or hardware problem or even drivers. You can try to disable the tooltips and see if that helps (check the FAQ on the wiki).

**Comment by lxaphir** [comment] 2021-03-31 06:21
Hello bcssov, I have everything working currently, except for this issue, which I am seeing also.  I was in a resolve edit, and the window vaporized.  Going back in to try to complete the edit again

**Comment by bcssov** [comment] 2021-03-31 12:13
These are separate issues, Irony should have logged something in its logs. Bring them and open a new ticket. I'm going to go ahead and close this one with this.

**Closed by bcssov** 2021-03-31 12:13 UTC
