### ISSUE TITLE
Add vanilla file to compare list in conflict solver

### ISSUE THREAD

**Issue by animusyosho** [bcssov/IronyModManager#237] opened 2021-04-23 22:04 UTC
It would be really nice to be able to easily see the vanilla file being replaced (when one exists) during mod conflicts. This can really help to understand "what and why is being changed" in order to assist in making decisions on if or how to resolve conflicts. 

I've considered symlinking vanilla content as an "ancestor mod" at the top of load order, but this would result in probably thousands of conflict resolutions when I am only really interested in seeing the vanilla file in the case of two or more mod files conflicting.

**Comment by bcssov** [comment] 2021-04-23 23:15
Duplicate of #11

**Closed** 2021-04-23 23:16 UTC
Labels: duplicate

**Comment by animusyosho** [comment] 2021-04-23 23:18
Thanks, I searched but did not find that one. Cheers!
