### ISSUE TITLE
Merging will result in a corrupted mod.

### ISSUE THREAD

**Issue by tatsujb** [bcssov/IronyModManager#421] opened 2023-01-12 04:56 UTC
tried with this mod pack https://steamcommunity.com/sharedfiles/filedetails/?id=1220270825 (which I can't load period; me merging was my attempt to fix this)

```
Failed to load module "canberra-gtk-module"
[systemsettings.cpp:44] CPU Model: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

[systemsettings.cpp:45] CPU Speed: 3663MHz

[systemsettings.cpp:46] CPU Physical Cores: 6

[systemsettings.cpp:47] CPU Logical Cores: 12

[systemsettings.cpp:48] System Memory: 31958

[systemsettings.cpp:49] OS: Linux;5.15.0-57-generic;#63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022;x86_64

[systemsettings.cpp:50] OS Language: 

[S_API] SteamAPI_Init(): Loaded '/home/t/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 281990
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198023671480 [API loaded no]
[virtualfilesystem_physfs.cpp:339] Failed to mount /home/t/.steam/debian-installation/steamapps/common/Stellaris/dlc/dlc004_plantoid/dlc004.zip with error unsupported

[virtualfilesystem_physfs.cpp:339] Failed to mount /home/t/.steam/debian-installation/steamapps/common/Stellaris/dlc/dlc013_horizon_signal/dlc013.zip with error unsupported

[virtualfilesystem_physfs.cpp:339] Failed to mount /home/t/.steam/debian-installation/steamapps/common/Stellaris/dlc/dlc015_anniversary/dlc015.zip with error unsupported

[virtualfilesystem_physfs.cpp:722] File '/home/t/.local/share/Paradox Interactive/Stellaris/mod/(Merged)_(Merged)_test/(Merged_test)_(Merged)_test.zip' does not exist : not found

[virtualfilesystem_physfs.cpp:339] Failed to mount /home/t/.local/share/Paradox Interactive/Stellaris/mod/(Merged)_(Merged)_test/(Merged_test)_(Merged)_test.zip with error corrupted
```

**Comment by bcssov** [comment] 2023-01-12 07:26
What exactly am I supposed to be looking at here? If a zip is corrupt it means the process failed for some reason. Retry and see what happens.

**Comment by tatsujb** [comment] 2023-01-12 14:08
it did this : 

```
./IronyModManager
[systemsettings.cpp:44] CPU Model: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

[systemsettings.cpp:45] CPU Speed: 3301MHz

[systemsettings.cpp:46] CPU Physical Cores: 6

[systemsettings.cpp:47] CPU Logical Cores: 12

[systemsettings.cpp:48] System Memory: 31958

[systemsettings.cpp:49] OS: Linux;5.15.0-57-generic;#63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022;x86_64

[systemsettings.cpp:50] OS Language: 

[S_API] SteamAPI_Init(): Loaded '/home/t/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 281990
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198023671480 [API loaded no]
[virtualfilesystem_physfs.cpp:339] Failed to mount /home/t/.steam/debian-installation/steamapps/common/Stellaris/dlc/dlc004_plantoid/dlc004.zip with error unsupported

[virtualfilesystem_physfs.cpp:339] Failed to mount /home/t/.steam/debian-installation/steamapps/common/Stellaris/dlc/dlc013_horizon_signal/dlc013.zip with error unsupported

[virtualfilesystem_physfs.cpp:339] Failed to mount /home/t/.steam/debian-installation/steamapps/common/Stellaris/dlc/dlc015_anniversary/dlc015.zip with error unsupported

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2494712590' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2899261406' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1728214912' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2857350778' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2268189539' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2512152163' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1960052542' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1993869579' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2908888919' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2786371128' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2794110773' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2027051983' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1833957813' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2779148236' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2434790082' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2780180614' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/682691478' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2053505347' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/902204956' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2458024521' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1227620643' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2717193796' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1998204784' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2574175110' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1641807098' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1255082381' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/946222466' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2807778592' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2028670202' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2648658105' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2774987343' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1121692237' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2863854446' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2806903835' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/865040033' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1793768254' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2670674796' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2907769573' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2293169684' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1506081421' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2441507863' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/727000451' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2877122349' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2476102240' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2686810902' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/819148835' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2898623879' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1732437279' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2284514368' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1732447147' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1878751971' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1960179456' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1740165239' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2158207688' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1999328266' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/937289339' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2895723911' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1199002146' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2815767345' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2790961377' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2130835957' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1834615504' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2044258989' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2438313459' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2775160404' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1928831043' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1934610438' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2786268200' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1693982756' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/850721710' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2491283817' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2183551683' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2774388842' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2517213262' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2612941355' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2785777242' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2805620150' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1419304439' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1504307690' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1481972266' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1623423360' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2288335512' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1595876588' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2807759164' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2178603631' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2769148429' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2821188750' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2905479647' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2607042792' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1813390120' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1623423504' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1890399946' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2608299248' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1610578060' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1629519297' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1628912584' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1630649870' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2411818376' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2641256974' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2475302050' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2466607238' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/1688887083' does not exist : not found

[virtualfilesystem_physfs.cpp:722] File '/home/t/.steam/debian-installation/steamapps/workshop/content/281990/2782639454' does not exist : not found

Trying to Write minidump to dir: /home/t/.local/share/Paradox Interactive/Stellaris/crashes/stellaris_20230112_150506/
Created Minidump: /home/t/.local/share/Paradox Interactive/Stellaris/crashes/stellaris_20230112_150506//91e05705-f8a5-4916-df03069e-0c0fb177.dmp
```

it always crashes at 80% load for this mod pack.

**Comment by bcssov** [comment] 2023-01-12 14:54
This would appear to be the issue; but if Irony can load, parse and merge stuff it's not an Irony issue but a game issue. You said game loads and crashes at 80%? You need to start from there as this is beyond Irony support. Check permissions etc

Alternatively if the game still loads fine if you ignore the warnings this still is not an Irony issue but then a load order issue as CTDs are usually caused by using outdated mods (mods editing gui files) or invalid mod load order.

**Comment by tatsujb** [comment] 2023-01-12 15:20
alright any way for me to know which mods are at issue?

I'm having to brute force and it's taking me weeks of trial and error now.

**Comment by bcssov** [comment] 2023-01-12 15:34
The hard way: binary search.
1. Delete folder after folder from the merged mod to identify which folder\file causes CTD
2. Exclude mod after mod and merge and see if that causes CTD

**Closed** 2023-01-12 23:56 UTC
Labels: question
