### ISSUE TITLE
Add New uncompressed mods to compressed Collection will zip it automaticlly.

### ISSUE THREAD

**Issue by MADxingjin** [bcssov/IronyModManager#462] opened 2023-09-21 10:49 UTC
**Is your feature request related to a problem? Please describe.**
Merged a collection. found modsth missing, appended to collection. all mods but modsth are merged and there is no button to compress single mod only.
had to compress the entire collection again, the name of compressed mods becomes messy and unhumanreadable.

**Describe the solution you'd like**
A button for compressing single selected mod.

**Describe alternatives you've considered**
Detection of sparse file mods added to merged collection and merge all of them again.

` 
foreach(var mod in collection){
   if(!mod.compressed)
     { CompressSingle(mod);}
 }
`

**Comment by bcssov** [comment] 2023-09-22 02:03
Duplicate of: https://github.com/bcssov/IronyModManager/issues/435

**Closed** 2023-10-01 00:02 UTC
Labels: duplicate, wontfix
