### ISSUE TITLE
Imm works without msttcorefonts rpm installed until conflict resolution is attempted

### ISSUE THREAD

**Issue by lxaphir** [bcssov/IronyModManager#229] opened 2021-04-06 23:34 UTC
**Describe the bug**
For Tumbleweed release 20210316:

Imm starts up normally without msttcorefonts.  However it is unable to proceed past 100% of conflict resolution without segfaulting.  Reinstalling msttcorefonts resolves the problem.

**To Reproduce**
1.  Install msttcorefonts-2.0-11.1.noarch.rpm
2.  Test latest Imm version v1.14.41
3.  Uninstall msttcorefonts rpm
4.  Retest Imm v1.14.41

**Expected behavior**
Successful conflict resolve

**Screenshots**
N/A

**Logs**
Application segfaulted

**Version:**
 - OS: Tumbleweed 20210316
 - Irony Version v1.14.41

**Additional context**
It almost works.

**Comment by bcssov** [comment] 2021-04-06 23:39
Does Irony generate any logs?

**Comment by lxaphir** [comment] 2021-04-07 00:15
This is all I get at console:

adm0@stellaris:~/bin/irony> ./IronyModManager
Segmentation fault (core dumped)
adm0@stellaris:~/bin/irony>


Also, that's with the latest 42, with window fix.

This is what my nlog.config looks like:

<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets>
    <target name="logger" xsi:type="File" fileName="${specialfolder:folder=ApplicationData}/Mario/IronyModManager-Logs/${date:format=yyyy-MM-dd}_${level}.log"
      layout="${longdate} ${message} ${exception:format=tostring}" maxArchiveDays="10"/>
    <target name="logconsole" xsi:type="Console"/>
    <target name="trace" xsi:type="trace" layout="Layout"/>
  </targets>

  <rules>
    <logger name="*" minLevel="Error" writeTo="logger"/>
    <logger name="*" minlevel="Error" writeTo="logconsole"/>
    <logger name="*" minLevel="Error" writeTo="trace"/>
  </rules>
</nlog>

**Comment by lxaphir** [comment] 2021-04-07 00:28
Hm, code didn't post.  Let me go with pastebin.

**Comment by lxaphir** [comment] 2021-04-07 00:29
https://pastebin.com/zesVgJd1

**Comment by lxaphir** [comment] 2021-04-07 00:36
Can I change this to something more relevant to the system (like in /tmp dir) and get some output?

'fileName="${specialfolder:folder=ApplicationData}/Mario/IronyModManager-Logs/${date:format=yyyy-MM-dd}_${level}.log"'

**Comment by lxaphir** [comment] 2021-04-07 00:47
Mario, tried to get some output by changing the nlog.config like so:

https://pastebin.com/6dtAxBBX

Didn't get any output in /tmp.

**Comment by bcssov** [comment] 2021-04-07 01:55
Well that's odd that it didn't even produce a log. But at least it's plausible that it's the font package involved somehow.

How does fonts.conf look like for you?
What is the output of fc-list?
What is the output of fc-match?

**Comment by lxaphir** [comment] 2021-04-08 12:13
Hey Mario, the log configuration details made all the difference in the generation of logs.  I have three logs for you now in /tmp, will upload those.  Also I am including the output of fc-list and fc-match for you, along with fonts.conf.  The console also had more information this time, when the segfault occurred here are the last few lines:


2021-04-08 07:55:25.7115|INFO|ReactiveUI.MessageBus|Listening to IronyModManager.Common.Events.SelectedGameChangedEventArgs:
2021-04-08 07:55:25.7366|INFO|ReactiveUI.MessageBus|Listening to IronyModManager.Common.Events.LocaleChangedEventArgs:
2021-04-08 07:55:25.7366|INFO|ReactiveUI.MessageBus|Listening to IronyModManager.Common.Events.SelectedGameChangedEventArgs:
2021-04-08 07:55:25.7366|INFO|ReactiveUI.MessageBus|Listening to IronyModManager.Common.Events.ForceClosePopulsEventArgs:
2021-04-08 07:55:25.7379|INFO|ReactiveUI.MessageBus|Listening to IronyModManager.Common.Events.LocaleChangedEventArgs:
2021-04-08 07:55:25.7379|INFO|ReactiveUI.MessageBus|Listening to IronyModManager.Common.Events.SelectedGameChangedEventArgs:
Segmentation fault (core dumped)
adm0@stellaris:~/bin/irony>


One note for you to consider -- the fonts on this system are just distribution and X11 specific fonts, I did not go out of my way to install anything extra.  Therefore this selection of fonts should be just about as generic as you can get for Linux distributions.  Fyi.

Also, the output of fc-match was interesting, there was only one match, and that was Cantarell Regular.

Was just looking at the post options here -- there does not look like there's a way to upload log files directly.

**Comment by lxaphir** [comment] 2021-04-08 12:24
Mario, can I attach logs to this case or is that not even possible here?

**Comment by lxaphir** [comment] 2021-04-08 12:36
test

**Comment by lxaphir** [comment] 2021-04-08 12:41
Trying to upload the error logs but getting the following message:

"Something went really wrong, and we can't process that file.  Try again."

**Comment by bcssov** [comment] 2021-04-08 13:03
Try pastebin or something then. If you have an adblocker or noscript or whatever it could cause such problems with uploads. For me it's literally just dragging and dropping and the upload completes. 

As for your fonts, you have significantly less fonts then what is installed on my clean VM openSUSE install. IDK, if we cannot get to the bottom of this it will probably mean that you'll need to have some of these font packages installed. For example I do not have installed this package that you had to install and Irony works with no problems.

**Comment by lxaphir** [comment] 2021-04-08 13:36
Ah, not it's not that I have less fonts, it's what was matched.  There was only one font match from your fc-match command,  but there's a crapton of fonts installed.  They just aren't being registered with Imm.

You need to check the output of fc-list in fc-list.log.

[fc-match.log](https://github.com/bcssov/IronyModManager/files/6278953/fc-match.log)
[fc-list.log](https://github.com/bcssov/IronyModManager/files/6278955/fc-list.log)
[2021-04-08_Warn.log](https://github.com/bcssov/IronyModManager/files/6278958/2021-04-08_Warn.log)
[2021-04-08_Info.log](https://github.com/bcssov/IronyModManager/files/6278960/2021-04-08_Info.log)
[2021-04-08_Error.log](https://github.com/bcssov/IronyModManager/files/6278961/2021-04-08_Error.log)
[fonts.conf.txt](https://github.com/bcssov/IronyModManager/files/6279002/fonts.conf.txt)

**Comment by lxaphir** [comment] 2021-04-08 13:38
Had to set Umatrix to allow this site.

**Comment by bcssov** [comment] 2021-04-08 17:33
FC Match on a clean install yields:
```Roboto-Regular.ttf: "Roboto" "Regular"```

fc-list yields: [fc-list.txt](https://github.com/bcssov/IronyModManager/files/6280422/fc-list.txt)

You can try these 2 separate dlls I compiled. Replace these in the irony install directory and try running I'm really curious whether one of these will work:
[variant 1.zip](https://github.com/bcssov/IronyModManager/files/6280429/variant.1.zip)
[variant 2.zip](https://github.com/bcssov/IronyModManager/files/6280430/variant.2.zip)

The logs don't tell anything useful and this issue has entered beyond edge case territory now.

**Comment by lxaphir** [comment] 2021-04-09 14:27
Okies, thanks for the interesting Imm generations, I will test them when I go off shift.  Looking forward to it.

Logs may be useless but I will generate warn-info-error on both.

**Comment by lxaphir** [comment] 2021-04-09 14:54
Ok, I admit it, I could not wait.  I might be late for work.  It was very interesting -- both variants are success, working with no problems.  Also, I havent put a stopwatch to it yet but I could swear both these variants are processing faster than the default 1.14.42.

So yeah, you pretty much nailed it bigtime whatever the nail was.  Since they worked, I didn't take time to get logs on them.  What exactly was the problem?

**Comment by bcssov** [comment] 2021-04-09 17:18
Trouble with matching character fonts in the Avalonia base logic. Not sure why exactly though. But the problem is this method:
https://github.com/bcssov/IronyModManager/blob/7e9b0c31a22bf60a81d7427187e9cef38f6a1c52/src/IronyModManager.Platform/Fonts/FontManager.cs#L136-L139

Variant 1 code partially overrode this method
```cs
            if (typefaces == null)
            {
                typefaces = new List<Typeface>();
                foreach (var item in fontFamilyManager.GetAllFontNames())
                {
                    typefaces.Add(new Typeface(fontFamilyManager.ResolveFontFamily(item).GetFontFamily()));
                }
            }
            foreach (var item in typefaces)
            {
                if (item.GlyphTypeface.GetGlyph((uint)codepoint) == 0)
                {
                    continue;
                }
                typeface = new Typeface(item.FontFamily.Name, fontStyle, fontWeight);
                return true;
            }

            return fontManager.TryMatchCharacter(codepoint, fontStyle, fontWeight, fontFamily, culture, out typeface);
```

Variant 2 code completely overrode this method

```cs
            if (typefaces == null)
            {
                typefaces = new List<Typeface>();
                foreach (var item in fontFamilyManager.GetAllFontNames())
                {
                    typefaces.Add(new Typeface(fontFamilyManager.ResolveFontFamily(item).GetFontFamily()));
                }
            }
            foreach (var item in typefaces)
            {
                if (item.GlyphTypeface.GetGlyph((uint)codepoint) == 0)
                {
                    continue;
                }
                typeface = new Typeface(item.FontFamily.Name, fontStyle, fontWeight);
                return true;
            }

            var fallback = SKFontManager.Default.MatchCharacter(fontFamily?.Name, (SKFontStyleWeight)fontWeight,
                SKFontStyleWidth.Normal, (SKFontStyleSlant)fontStyle, new string[] { culture.ThreeLetterISOLanguageName, culture.TwoLetterISOLanguageName }, codepoint);

            typeface = new Typeface(fallback?.FamilyName ?? fontFamilyManager.GetDefaultFontFamily().GetFontFamily(), fontStyle, fontWeight);

            return true;
```

Of course variant 1 will be in the official new release.

**Comment by lxaphir** [comment] 2021-04-10 01:02
Mario, can you give me a little more time to experiment with these variants?  It looks like variant 1 segfaulted on me once.  What happened was that everything was working so well I wanted to ensure that 1.14.42 was consistent in fails.  So I loaded 42 vanilla and I replicated the segfault as expected.  But then, I loaded variant 1 on top of that 42 install, and reattempted conflict resolve.  It segfaulted.  I was like, wth..  So then I immediately loaded variant 2 files into the 42 install and tried it again.  Worked.  I was like, ok can I replicate this variant 1 fail again?  So I loaded variant 1; and it worked.

So the first thought I had was, did the vanilla 42 segfault cause the variant 1 segfault, since the test was back to back?  Or is variant 2 a better version?  Variant 2 followed a segfault also, but it worked afterwards.  So I'm planning to check this out tonight.

**Comment by bcssov** [comment] 2021-04-10 13:47
Variant 1 should be a "better" version as it still calls base logic (via proxy) if it fails at something. I've already pushed variant 1 to the master branch. That's the best I can do in this case.

**Comment by lxaphir** [comment] 2021-04-10 15:31
Ok, well I went ahead and did what I promised you I would do, I went back and tested more thoroughly rather than do a quick hit and run before I have to go to work.  Bear in mind that the results are the results and not flavored to personal preference, I'm just presenting what is happening regardless of convenience or predisposition.  Variant 1 is showing inconsistent results and crashes; Variant 2 gives consistent working results.

**Comment by lxaphir** [comment] 2021-04-10 15:42
What I would probably say at this point is, since you have got this in the master branch, and we know now what is going on, we go ahead and evaluate the new build as a whole after it's generated as a new release and see what happens.  The new build after it's constructed may not behave as these variant 1 tests are behaving.

**Comment by v-evets** [comment] 2021-04-16 12:36
Looks like I'm seeing the same problem.

Gentoo GNU/Linux 2.6 amd64
corefonts installed (FWIW)

With reference to the test builds posted above:
1.15.16 release reliably segfaults trying to load the conflict solver results window.
Variant 1 reliably segfaults trying to load the conflict solver results window.
Variant 2 successfully completes and displays the solver results.

Log output from 1.15.16 release:
[2021-04-17_Info.log](https://github.com/bcssov/IronyModManager/files/6325015/2021-04-17_Info.log)
[2021-04-17_Warn.log](https://github.com/bcssov/IronyModManager/files/6325016/2021-04-17_Warn.log)
[2021-04-17_Error.log](https://github.com/bcssov/IronyModManager/files/6325018/2021-04-17_Error.log)

**Closed** 2021-04-16 19:20 UTC
Labels: bug
