### ISSUE TITLE
The launcher has an issue with applying mods to Stellaris

### ISSUE THREAD

**Issue by EclipseNoodle** [bcssov/IronyModManager#426] opened 2023-02-19 19:41 UTC
The Launcher does not apply mods to Stellaris for some reason.

No clue how to reproduce, happened randomly. Was working fine earlier in the day.

**Expected behavior**

**Logs**
2023-02-19 20:36:12.9883 Version: 1.24.114+164e09e574
OS Description: Microsoft Windows 10.0.22621
Runtime Identifier: win10-x64
 Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: description'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.ExecuteQueryAsyncInternalForType[TResult](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, String traceKey, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, CancellationToken cancellationToken, String tableName, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.ExecuteQueryAsyncInternal[TResult](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, String traceKey, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, CancellationToken cancellationToken, String tableName, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.QueryAllAsyncInternalBase[TEntity](IDbConnection connection, String tableName, IEnumerable`1 fields, IEnumerable`1 orderBy, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.QueryAllAsyncInternal[TEntity](IDbConnection connection, String tableName, IEnumerable`1 fields, IEnumerable`1 orderBy, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.SyncModsV4Async(Playsets collection, ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 947
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.ExportAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 115
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass7_0.<<ApplyModsAsync>b__2>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 113
--- End of stack trace from previous location ---
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 116
   at IronyModManager.Services.ModService.ExportModsAsync(IReadOnlyCollection`1 enabledMods, IReadOnlyCollection`1 regularMods, IModCollection modCollection) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 254
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.ApplyCollectionAsync(Int64 id, Boolean showOverlay, Boolean validateParadoxLauncher) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 629

Stellaris is from GOG, if that helps in any way.

**Comment by bcssov** [comment] 2023-02-20 04:13
Read this [this](https://github.com/bcssov/IronyModManager/discussions/425) as you're probably on beta launcher. The cause is probably item 2.

**Comment by kirillgla** [comment] 2023-02-24 03:11
I ran into this issue, too. This issue is no longer limited to beta launchers. In case anyone else comes across this issue, here's a way to downgrade Stellaris launcher to an older version: you need to downgrade stellaris (in properties -> betas -> 3.6.0 rollback), then launch the launcher and enable betas, restart the launcher, disable betas, restart it again, and then update Stellaris back to the modern version

**Comment by bcssov** [comment] 2023-02-25 20:03
One can resolve this by deleting pdxl auncher sqlite databases. I've pushed a fix for this but have no time to test at the moment. Going to maybe deal with it at a later date, breaking compatibility between pdx launcher and irony came very soon once the retirement of Irony was announced.

**Comment by bcssov** [comment] 2023-03-14 05:18
"also bonus typo issue. "ocurred" should be "occurred".)"

**Closed** 2023-03-14 20:24 UTC
Labels: feature
