### ISSUE TITLE
Bunch of improvement requests/ suggestions

### ISSUE THREAD

**Issue by Arkhorse** [bcssov/IronyModManager#212] opened 2021-03-22 22:07 UTC
I'm going to forgo the template, as it doesn't really fit here.

First, I am a contributor to a project called "Relhax Modpack". This modpack is in CS code, so its code may help you guys out. The Dev/s are professionals, so maybe something good there. Link: https://github.com/Willster419/RelhaxModpack. It is open source, but if you have any questions, join our discord and ask Willster, or just post an issue. Note: I don't personally do much in the way of programing the application, I handle the database side of it along with others.

Now on to the actual requests/ suggestions

- The Export and Import buttons could be changed to all have their own buttons. There is more than enough room up there to do this. And with dynamic resizing of buttons, would support the app being in different resolutions
- Add a "Refresh" Button to refresh the apps mod definitions, so the app can import newly downloaded or created mods without needing to relaunch the app. EDIT: Ignore this, I didnt see the button in the right click menu. Maybe move it to beside the actions button?
    - Simply importing things tends to break the patch mods. Guess this is a bug.
- Add the ability to contribute compatibility patches to a database to others can use them instead of making their own. These could be saved in xml format, and pulled/pushed to the GitHub or a ftp server (wouldn't need to be a large one)
    - If you use GitHub, you could use discord for users to upload their own patches, or simply a google form.
- More obvious conflict wins. Sometimes its hard to tell exactly which mod is winning the conflict. Maybe a simple check mark would suffice.
- Save ignore rules. This one is rather annoying. I have to constantly remake any ignore rules I put in either after an app relaunch, or with other profiles/ collections.
- Load Order Optimization Tool (Like LOOT from the Fallout games). Like with the mod compatibility patch database, there could be a system to auto sort mods to where they need to be, and leave any mod not known at the top for the user to manually sort.
    - Loot also has the ability to know if a user should have certain patch mods installed, and link them to the user. Could also be useful
 - The ability to do something like the ignore rule modName, but altered. This rule would simply say that this mod should always lose, or this mod should always win.
     - District Overhaul 2 would be an always win, !!Ariphaos Unofficial Patch would always lose.

Well, thats all I can think of right now. Will update this with another section if I think of anymore.

**Comment by bcssov** [comment] 2021-03-23 01:07
> This modpack is in CS code, so its code may help you guys out. The Dev/s are professionals, so maybe something good there

So am I :)  
But honestly it's difficult to use someone else’s code designed for a completely different reason in another unrelated app. But thanks anyway.

> The Export and Import buttons could be changed to all have their own buttons. There is more than enough room up there to do this. And with dynamic resizing of buttons, would support the app being in different resolutions

While I'm no UX expert myself obviously (I'm a developer). I'd prefer to keep the buttons as they are, I could develop various viewports to keep a "responsive" philosophy in place here, so the layout would change. But given how now Irony supports multiple languages and being very easy to add another language, that'll mean too many problems for me down the line. Even now there are problems as text in some of the localizations is too wide. Secondly if the buttons are stacked in more rows this will mean less space for mod management as the listbox where the mods are located would lose some space.

> Simply importing things tends to break the patch mods. Guess this is a bug.

Too little information for me to reply. I was not made aware of any existing issues in that department. What I could possibly see potentially confusing you is Irony stating that conflict solver needs a rerun each time the collection (playset) is changed. That is intentional and not an issue or a bug. While Irony does not do any auto patching it does do some automated fixing behind the scenes and any change in the load order potentially requires a conflict solver re-run.

> Add the ability to contribute compatibility patches to a database to others can use them instead of making their own. These could be saved in xml format, and pulled/pushed to the GitHub or a ftp server (wouldn't need to be a large one) 

That was actually a plan but given how I'm a one man army I had to give up on that idea. My main inspiration to how this would work would have been CKAN\NETKAN for Kerbal Space Program.

> More obvious conflict wins. Sometimes its hard to tell exactly which mod is winning the conflict. Maybe a simple check mark would suffice.

Irony already tells you what will win and why.
- Orange borders around an item indicate what will be used by default by the game
- Green borders indicate a virtual definition which, if resolved (diff merged) will override anything that's listed. The virtual definition uses orange definition content as the starting point. The idea behind it is to do diff merging with all the definitions into the green one.

> Save ignore rules. This one is rather annoying. I have to constantly remake any ignore rules I put in either after an app relaunch, or with other profiles/ collections.

I opted against the global ignore rules logic as each mod collection is different, so they were made per mod patch. If you delete patches the ignore rules will be lost, same as if you have multiple mod collections which have their own mod patches they will not be synced as they are per mod patch (per collection).

> Load Order Optimization Tool (Like LOOT from the Fallout games). Like with the mod compatibility patch database, there could be a system to auto sort mods to where they need to be, and leave any mod not known at the top for the user to manually sort.

It's also has been a point of discussion on the Irony's stellaris modding den channel. The problem is that very little to no people are willing to help on this one. Thus such a feature would be a waste of time and resources I can dedicate to this project (of which I have very little time as it is at the moment). Simply putting it it's hard to motivate people of Stellaris community for some reason. I also planned to borrow ideas from how patching is done from KSP ModuleManager onto stellaris (it would of course happen before launching the game) but that too was cut for the same reason.

> The ability to do something like the ignore rule modName, but altered. This rule would simply say that this mod should always lose, or this mod should always win. 

I like that. 

After more info is gathered this will have to be broken down into smaller sub sections, I'm not a fan of a single giant issue with various unrelated topics.

**Closed** 2021-03-23 18:26 UTC
Labels: feature
