### ISSUE TITLE
Mod Manager takes over a minute to Launch the game

### ISSUE THREAD

**Issue by japa4551** [bcssov/IronyModManager#412] opened 2022-11-16 21:05 UTC
**Describe the bug**
For some reason on Linux, the Mod Launcher takes a significant while to launch the game. The issue has not happened before while i was on Windows, only a minor slow app start.

**To Reproduce**
1. Open the Irony Mod Manager
2. Select a Playset
3. Click Play
4. Wait for a minute or more for the game to launch

**Expected behavior**
The Launcher should've launch the game in a maximum of 10 seconds (from my experience at least)

** Extra Info **
Mod Manager Version: v1.24.81

![image](https://user-images.githubusercontent.com/5614680/202294013-50fb1e6a-70d4-459e-9826-8fdf7a470070.png)

EDIT: After updating to v1.24.85 this crash started to happen
```
Unhandled error ocurred. Please use this information to file a bug report:

2022-11-16 20:31:22.8772 Version: 1.24.85+d60e54c3d1
OS Description: Linux 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000
Runtime Identifier: endeavouros-x64
 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/home/japa4551/Documents/Irony Mod Manager/IronyModManager.GameHandler' with working directory '/home/japa4551/Documents/Irony Mod Manager'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at IronyModManager.Shared.ProcessRunner.RunExternalProcess(String path, String args, Boolean waitForExit) in D:\Working\IronyModManager\src\IronyModManager.Shared\ProcessRunner.cs:line 110
   at IronyModManager.Services.ExternalProcessHandlerService.LaunchSteamAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ExternalProcessHandlerService.cs:line 110
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass177_0.<<OnActivated>g__ensureSteamIsRunning|21>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 877
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass177_0.<<OnActivated>g__launchGame|22>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 924
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass177_0.<<OnActivated>b__23>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 954
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 73
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 561
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 507
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler scheduler, ObserveOnObserverNew`1 self) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 497
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 97


```

**Comment by japa4551** [comment] 2022-11-17 01:13
I've spoken with [bcssov](https://github.com/bcssov) and i was able to temporarily fix this issue i've just had to set those variables in **appSettings.json** (Irony Mod Manager Installation Folder)
`
   "UseLegacyLaunchMethod": true,
    "UseGameHandler": false,
`

**Comment by bcssov** [comment] 2022-11-17 06:52
Fixed. Caused by refactoring I forgot to put quotes around the command to set chmod permissions. This refactoring also probably broke autoupdate sadly.

It's fixed in the latest version. To make these settings permanent (Irony update will always overwrite appSettings.json). Copy appSettings.json file and name the copy appSettingsOverride.json (Irony applies partial json merge so you don't have to keep syncing the config files or anything).

**Closed by bcssov** 2022-11-17 06:52 UTC
Labels: bug
